service: subreddits-rest-api

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "cloudformation:CreateStack"
        - "cloudformation:DeleteStack"
        - "cloudformation:DescribeStack*"
        - "cloudformation:UpdateStack"
        - "cloudwatch:GetMetricStatistics"
        - "iam:ListInstanceProfiles"
        - "iam:ListRoles"
        - "iam:PassRole"
      Resource: "*"
custom:
  stage: prod

package:
  include:
    - libraries/**
    - .so/**
  exclude:
    - .git/**
    - lambda/**

functions:
  getTop10ByPoints:
    handler: rest_api.get_top_10_by_points
    events:
      - http:
          method: get
          path: top10punctuation
          integration: lambda
          timeout: 20000
    timeout: 90
    name: subreddits-rest-api-top10-points
    description: Get top 10 by points

  getTop10ByComments:
    handler: rest_api.get_top_10_by_num_comments
    events:
      - http:
          method: get
          path: top10comments
          integration: lambda
          timeout: 20000
    timeout: 90
    name: subreddits-rest-api-top10-comments
    description: Get top 10 by number of comments
